name       : python-nbxmpp
version    : 0.6.8
release    : 7
source     :
    - https://files.pythonhosted.org/packages/24/54/23a475a0d7d3664ea21b14ce907245dc390496f31d229a9aac2ae20c7c28/nbxmpp-0.6.8.tar.gz : 8c2b4b8aac1a8c6d07c1e30af542fde20a70a9b8c7c04017e9cea0db654437c6
homepage   : https://python-nbxmpp.gajim.org
license    : GPL-3.0-later
component  : programming.python
summary    : Python Jabber/XMPP library for Gajim
description: |
    python-nbxmpp is a Python library that provides a way for Python applications to use Jabber/XMPP networks in a non-blocking way. This library is initialy a fork of xmpppy one, but using non-blocking sockets.
rundeps    :
    - python3-gobject
    - python-openssl
build      : |
    %python3_setup
install    : |
    %python3_install
