name       : python-nbxmpp
version    : 3.2.4
release    : 16
source     :
    - https://files.pythonhosted.org/packages/source/n/nbxmpp/nbxmpp-3.2.4.tar.gz : 74deff4fc20603255571f7e0b4cd68157e44e1e769341e63d32dd846a291a615
homepage   : https://python-nbxmpp.gajim.org
license    : GPL-3.0-later
component  : programming.python
summary    : Library to connect to Jabber/XMPP networks in a non-blocking way
description: |
    python-nbxmpp is a Python library that provides a way for Python applications to use Jabber/XMPP networks in a non-blocking way.
rundeps    :
    - libsoup
    - python-gobject
    - python-idna
    - python-packaging
    - python-precis_i18n
build      : |
    %python3_setup
install    : |
    %python3_install
