name       : python-nbxmpp
version    : 0.6.2
release    : 3
source     :
    - https://files.pythonhosted.org/packages/source/n/nbxmpp/nbxmpp-0.6.2.tar.gz : 10bfb12b083a7509779298c31b4b61e2ed7e78d1960cbcfb3de8d38f3b830991
homepage   : https://python-nbxmpp.gajim.org
license    : GPL-3.0
component  : programming.python
summary    : Python Jabber/XMPP library for Gajim.
description: |
    python-nbxmpp is a Python library that provides a way for Python applications to use Jabber/XMPP networks in a non-blocking way. This library is initialy a fork of xmpppy one, but using non-blocking sockets.
build      : |
    %python_setup
install    : |
    %python_install
