name       : python-nbxmpp
version    : 0.5.4
release    : 2
source     :
    - https://pypi.python.org/packages/72/52/24915ef3ac4dbb96b987dac2bfc2ca5a7dba364798a6277f65bc59a7174e/nbxmpp-0.5.4.tar.gz : 0a85f92a23c7adea1ae932b5e9e0a4ee586ca79a4d0ebd0294b1b095d9314379
homepage   : https://python-nbxmpp.gajim.org
license    : GPL-2.0
component  : programming.python
summary    : Python Jabber/XMPP library for Gajim.
description: |
    python-nbxmpp is a Python library that provides a way for Python applications to use Jabber/XMPP networks in a non-blocking way. This library is initialy a fork of xmpppy one, but using non-blocking sockets.
build      : |
    %python_setup
install    : |
    %python_install
