name       : python-nbxmpp
version    : 4.3.2
release    : 18
source     :
    - https://files.pythonhosted.org/packages/source/n/nbxmpp/nbxmpp-4.3.2.tar.gz : ec3104504d5e90a10dc0ae3f11b0b50ec2e596d7e70d220676e0e390f1d006ac
homepage   : https://python-nbxmpp.gajim.org
license    : GPL-3.0-or-later
component  : programming.python
summary    : Library to connect to Jabber/XMPP networks in a non-blocking way
description: |
    python-nbxmpp is a Python library that provides a way for Python applications to use Jabber/XMPP networks in a non-blocking way.
builddeps  :
    - python-build
    - python-installer
    - python-packaging
    - python-wheel
rundeps    :
    - libsoup
    - python-gobject
    - python-idna
    - python-packaging
    - python-precis_i18n
build      : |
    %python3_setup
install    : |
    %python3_install
