name       : python-nbxmpp
version    : 0.6.6
release    : 5
source     :
    - https://files.pythonhosted.org/packages/source/n/nbxmpp/nbxmpp-0.6.6.tar.gz : d0e2830c75c5fa74871995f0be4c5ef2477e696f6ac38b4414170f86bd06e62e
homepage   : https://python-nbxmpp.gajim.org
license    : GPL-3.0-later
component  : programming.python
summary    : Python Jabber/XMPP library for Gajim
description: |
    python-nbxmpp is a Python library that provides a way for Python applications to use Jabber/XMPP networks in a non-blocking way. This library is initialy a fork of xmpppy one, but using non-blocking sockets.
rundeps    :
    - python3-gobject
    - python-openssl
build      : |
    %python3_setup
install    : |
    %python3_install
